import * as fs from 'node:fs'
import * as path from 'node:path'
import * as mcl from 'mcl-wasm'
import { getBytes, hexlify, toUtf8Bytes } from 'ethers'
import { BlsBn254 } from '@kevincharm/bls-bn254'
import { bn254 } from '@noble/curves/bn254'
import { DST } from '../src/constants'
import { splitSecret, partialSign, aggregate, groupPublicKey } from '../src/threshold'

// Deterministic test fixtures for the Solidity test-suite. These are TEST KEYS.
// Regenerate with `npm run gen:vectors`.

const GROUP_SEED = '0x000000000000000000000000000000000000000000000000000000000000f00d'
const N = 9
const T = 5

function frToBigInt(fr: mcl.Fr): bigint {
    return BigInt(hexlify(Uint8Array.from(Array.from(fr.serialize()).reverse())))
}

/** A point on the G2 twist that is NOT in the order-r subgroup. */
function twistPointOutsideSubgroup(): [bigint, bigint, bigint, bigint] {
    const Fp2 = bn254.fields.Fp2
    const b2 = bn254.params.G2b
    const PointG2 = bn254.shortSignatures.getPublicKey(new Uint8Array(32).fill(3)).constructor as any

    for (let c0 = 1n; c0 < 500n; c0++) {
        const x = Fp2.create({ c0, c1: 7n })
        const y2 = Fp2.add(Fp2.mul(Fp2.sqr(x), x), b2)
        let y
        try {
            y = Fp2.sqrt(y2)
        } catch {
            continue
        }
        if (!Fp2.eql(Fp2.sqr(y), y2)) continue
        const p = PointG2.fromAffine({ x, y })
        if (p.isTorsionFree()) continue // we want one that is not
        // deliberately not assertValidity(): noble rejects non-subgroup points
        return [x.c0, x.c1, y.c0, y.c1]
    }
    throw new Error('no non-subgroup twist point found')
}

async function main() {
    const bls = await BlsBn254.create()
    const dstBytes = toUtf8Bytes(DST)

    const { secretKey, pubKey } = bls.createKeyPair(GROUP_SEED)
    const groupPubKey = bls.serialiseG2Point(pubKey)

    const message = '0x' + '11'.repeat(32)
    const msgPoint = bls.hashToPoint(dstBytes, getBytes(message))
    const { signature } = bls.sign(msgPoint, secretKey)

    // 5-of-9 threshold signature over the same key, from two disjoint quorums
    const shares = splitSecret(bls, secretKey, T, N)
    const quorumA = [0, 1, 2, 3, 4].map((i) => partialSign(bls, shares[i], msgPoint))
    const quorumB = [4, 5, 6, 7, 8].map((i) => partialSign(bls, shares[i], msgPoint))

    // an unrelated key, for "signature from the wrong key" tests
    const wrong = bls.createKeyPair('0x00000000000000000000000000000000000000000000000000000000deadbeef')
    const wrongSig = bls.sign(msgPoint, wrong.secretKey).signature

    const vectors = {
        _comment: 'Generated by offchain/scripts/genVectors.ts. TEST KEYS ONLY.',
        dst: DST,
        threshold: T,
        operators: N,
        groupSecretKey: '0x' + frToBigInt(secretKey).toString(16).padStart(64, '0'),
        groupPubKey: groupPubKey.map((v) => '0x' + v.toString(16).padStart(64, '0')),
        wrongSecretKey: '0x' + frToBigInt(wrong.secretKey).toString(16).padStart(64, '0'),
        wrongPubKey: bls
            .serialiseG2Point(wrong.pubKey)
            .map((v) => '0x' + v.toString(16).padStart(64, '0')),
        message,
        messagePoint: bls
            .serialiseG1Point(msgPoint)
            .map((v) => '0x' + v.toString(16).padStart(64, '0')),
        signature: bls
            .serialiseG1Point(signature)
            .map((v) => '0x' + v.toString(16).padStart(64, '0')),
        thresholdSignatureQuorumA: bls
            .serialiseG1Point(aggregate(bls, quorumA))
            .map((v) => '0x' + v.toString(16).padStart(64, '0')),
        thresholdSignatureQuorumB: bls
            .serialiseG1Point(aggregate(bls, quorumB))
            .map((v) => '0x' + v.toString(16).padStart(64, '0')),
        wrongKeySignature: bls
            .serialiseG1Point(wrongSig)
            .map((v) => '0x' + v.toString(16).padStart(64, '0')),
        pubKeyOffSubgroup: twistPointOutsideSubgroup().map(
            (v) => '0x' + v.toString(16).padStart(64, '0'),
        ),
    }

    // sanity: the threshold aggregate must equal the single-key signature
    const full = vectors.signature.join()
    if (vectors.thresholdSignatureQuorumA.join() !== full) throw new Error('quorum A mismatch')
    if (vectors.thresholdSignatureQuorumB.join() !== full) throw new Error('quorum B mismatch')
    if (groupPublicKey(bls, shares.slice(0, T)).join() !== groupPubKey.join())
        throw new Error('group pk mismatch')

    const out = path.join(__dirname, '..', '..', 'test', 'vectors', 'bls.json')
    fs.mkdirSync(path.dirname(out), { recursive: true })
    fs.writeFileSync(out, JSON.stringify(vectors, null, 4) + '\n')
    console.log(`wrote ${out}`)
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
