// Command gen-dkg-vector runs a real DKG and writes what came out to
// test/vectors/dkg.json, where the Solidity test-suite picks it up.
//
// This is the end-to-end proof that the Go node and the deployed contract agree:
// keys and signatures that never touched the TypeScript reference still verify
// on-chain. CI regenerates it with a fresh ceremony on every run, so the claim
// is re-established rather than remembered.
package main

import (
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"math/big"
	"os"
	"path/filepath"

	"threshold-vrf/node/internal/blsvrf"
	"threshold-vrf/node/internal/dkg"
	"threshold-vrf/node/internal/threshold"
)

type vector struct {
	Comment     string   `json:"_comment"`
	Operators   int      `json:"operators"`
	Threshold   int      `json:"threshold"`
	Epoch       uint64   `json:"epoch"`
	GroupPubKey []string `json:"groupPubKey"`
	Seed        string   `json:"seed"`
	// Two disjoint quorums must yield byte-identical signatures.
	QuorumA          []uint32 `json:"quorumA"`
	SignatureQuorumA string   `json:"signatureQuorumA"`
	QuorumB          []uint32 `json:"quorumB"`
	SignatureQuorumB string   `json:"signatureQuorumB"`
	// Aggregated from one share too few: must not verify.
	SignatureBelowThreshold string `json:"signatureBelowThreshold"`
	// After a rotation that replaced one operator, against the same key.
	SignatureAfterRotation string `json:"signatureAfterRotation"`
}

func main() {
	n := flag.Int("operators", 9, "number of operators")
	t := flag.Int("threshold", 5, "signatures required")
	epoch := flag.Uint64("epoch", 1, "key epoch")
	out := flag.String("out", "", "output path (default: ../test/vectors/dkg.json)")
	flag.Parse()

	if err := run(*n, *t, *epoch, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(n, t int, epoch uint64, out string) error {
	shares, err := dkg.RunLocal(n, t, epoch)
	if err != nil {
		return fmt.Errorf("dkg: %w", err)
	}

	var seed [32]byte
	copy(seed[:], []byte("robinhood-chain threshold vrf"))

	pk, err := blsvrf.SerializeG2(shares[0].GroupPublic)
	if err != nil {
		return err
	}

	sigA, err := aggregate(shares, indices(0, t), seed, t, n)
	if err != nil {
		return err
	}
	sigB, err := aggregate(shares, indices(n-t, t), seed, t, n)
	if err != nil {
		return err
	}
	if sigA != sigB {
		return fmt.Errorf("two quorums disagreed: %s != %s", sigA, sigB)
	}

	// one short of the threshold: Lagrange still produces a point, it just is
	// not the group's signature
	short, err := aggregate(shares, indices(0, t-1), seed, t-1, n)
	if err != nil {
		return err
	}

	members := append(dkg.Members(shares)[1:], dkg.NewMember(uint32(n)))
	rotated, err := dkg.ResharLocal(shares, members, t, epoch+1)
	if err != nil {
		return fmt.Errorf("resharing: %w", err)
	}
	sigRotated, err := aggregate(rotated, indices(n-t, t), seed, t, n)
	if err != nil {
		return err
	}

	v := vector{
		Comment: "Generated by node/cmd/gen-dkg-vector from a real Pedersen DKG. " +
			"Randomised: regenerating it produces different keys that must verify just as well.",
		Operators:               n,
		Threshold:               t,
		Epoch:                   epoch,
		GroupPubKey:             []string{hexInt(pk[0]), hexInt(pk[1]), hexInt(pk[2]), hexInt(pk[3])},
		Seed:                    "0x" + hex.EncodeToString(seed[:]),
		QuorumA:                 shareIndices(shares, indices(0, t)),
		SignatureQuorumA:        sigA,
		QuorumB:                 shareIndices(shares, indices(n-t, t)),
		SignatureQuorumB:        sigB,
		SignatureBelowThreshold: short,
		SignatureAfterRotation:  sigRotated,
	}

	if out == "" {
		out = filepath.Join("..", "test", "vectors", "dkg.json")
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	body, err := json.MarshalIndent(v, "", "    ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(out, append(body, '\n'), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d of %d, epoch %d)\n", out, t, n, epoch)
	return nil
}

func indices(from, count int) []int {
	out := make([]int, count)
	for i := range out {
		out[i] = from + i
	}
	return out
}

func shareIndices(shares []dkg.Share, positions []int) []uint32 {
	out := make([]uint32, len(positions))
	for i, p := range positions {
		out[i] = shares[p].Index
	}
	return out
}

func aggregate(shares []dkg.Share, positions []int, seed [32]byte, t, n int) (string, error) {
	partials := make([]threshold.Partial, 0, len(positions))
	for _, p := range positions {
		partials = append(partials, threshold.Partial{
			Index: shares[p].Index,
			Sig:   blsvrf.Sign(shares[p].Secret, seed),
		})
	}
	sig, err := threshold.Aggregate(partials, t, n)
	if err != nil {
		return "", err
	}
	raw, err := blsvrf.SignatureBytes(sig)
	if err != nil {
		return "", err
	}
	return "0x" + hex.EncodeToString(raw), nil
}

func hexInt(n *big.Int) string {
	return "0x" + hex.EncodeToString(n.FillBytes(make([]byte, 32)))
}
