// Package blsvrf holds the exact BLS scheme the on-chain verifier accepts.
//
// Everything here is pinned by cross-implementation tests against
// test/vectors/bls.json, which is generated by the TypeScript stack and
// consumed by the Solidity tests. Three independent implementations have to
// agree byte for byte; a signature that fails any of them fails on-chain.
package blsvrf

import (
	"errors"
	"math/big"

	"github.com/drand/kyber"
	"github.com/drand/kyber/pairing/bn254"
	"github.com/drand/kyber/share"
)

// DST is the domain separation tag. It is fixed for the lifetime of the
// protocol and hard-coded identically in VRFVerifier.sol; changing it
// invalidates every signature that has ever been produced.
const DST = "RH-VRF-BN254G1_XMD:KECCAK-256_SVDW_RO_V1_"

// SignatureLength is what VRFCoordinator.fulfillRandomWords expects.
const SignatureLength = 64

// Suite returns the BN254 pairing suite configured with the protocol's DST.
//
// Note kyber names its default G1 tag "...SSWU_RO_" while the implementation is
// in fact the Shallue-van de Woestijne map of RFC 9380 section 6.6.1 — the same
// map the Solidity library uses. The tag is only a label, and we supply our own.
func Suite() *bn254.Suite {
	suite := bn254.NewSuite()
	suite.SetDomainG1([]byte(DST))
	return suite
}

// ScalarFromBytes interprets 32 big-endian bytes as a scalar of Fr.
func ScalarFromBytes(b []byte) kyber.Scalar {
	return Suite().G1().Scalar().SetBytes(b)
}

// HashSeedToPoint maps a coordinator seed onto G1, exactly as
// VRFVerifier.hashSeedToPoint does.
func HashSeedToPoint(seed [32]byte) kyber.Point {
	return Suite().G1().Point().(interface{ Hash([]byte) kyber.Point }).Hash(seed[:])
}

// Sign produces sigma = secret * H(seed). Called with a DKG share this is a
// partial signature; called with the whole group secret it is the group
// signature itself. The two are indistinguishable by construction, which is
// why aggregating t partials yields exactly the latter.
func Sign(secret kyber.Scalar, seed [32]byte) kyber.Point {
	h := HashSeedToPoint(seed)
	return h.Mul(secret, h)
}

// PublicKey returns secret * G2.
func PublicKey(secret kyber.Scalar) kyber.Point {
	return Suite().G2().Point().Mul(secret, nil)
}

// Verify checks a group signature the same way the contract does:
// e(sigma, G2) == e(H(seed), pk).
func Verify(pub kyber.Point, seed [32]byte, sig kyber.Point) bool {
	suite := Suite()
	left := suite.Pair(sig, suite.G2().Point().Base())
	right := suite.Pair(HashSeedToPoint(seed), pub)
	return left.Equal(right)
}

// SerializeG1 returns (x, y) in the order the EVM expects.
func SerializeG1(p kyber.Point) ([2]*big.Int, error) {
	var out [2]*big.Int
	raw, err := p.MarshalBinary()
	if err != nil {
		return out, err
	}
	if len(raw) != 64 {
		return out, errors.New("blsvrf: unexpected G1 encoding length")
	}
	out[0] = new(big.Int).SetBytes(raw[0:32])
	out[1] = new(big.Int).SetBytes(raw[32:64])
	return out, nil
}

// SerializeG2 returns the group key as [x.c0, x.c1, y.c0, y.c1].
//
// kyber marshals G2 as (x.c1 || x.c0 || y.c1 || y.c0) — imaginary part first —
// so the halves are swapped here to match VRFVerifier's constructor argument.
func SerializeG2(p kyber.Point) ([4]*big.Int, error) {
	var out [4]*big.Int
	raw, err := p.MarshalBinary()
	if err != nil {
		return out, err
	}
	if len(raw) != 128 {
		return out, errors.New("blsvrf: unexpected G2 encoding length")
	}
	out[0] = new(big.Int).SetBytes(raw[32:64])
	out[1] = new(big.Int).SetBytes(raw[0:32])
	out[2] = new(big.Int).SetBytes(raw[96:128])
	out[3] = new(big.Int).SetBytes(raw[64:96])
	return out, nil
}

// SignatureBytes encodes a G1 signature as the 64 bytes the coordinator takes.
func SignatureBytes(sig kyber.Point) ([]byte, error) {
	raw, err := sig.MarshalBinary()
	if err != nil {
		return nil, err
	}
	if len(raw) != SignatureLength {
		return nil, errors.New("blsvrf: unexpected signature length")
	}
	return raw, nil
}

// PointFromSignature parses the 64-byte on-chain encoding back into a G1 point.
func PointFromSignature(raw []byte) (kyber.Point, error) {
	if len(raw) != SignatureLength {
		return nil, errors.New("blsvrf: signature must be 64 bytes")
	}
	p := Suite().G1().Point()
	if err := p.UnmarshalBinary(raw); err != nil {
		return nil, err
	}
	return p, nil
}

// SharePublicKey derives operator `index`'s public key from the DKG's public
// commitments. Every participant can compute it for every other participant,
// which is what makes a partial signature checkable by its recipient.
func SharePublicKey(commits []kyber.Point, index uint32) kyber.Point {
	return share.NewPubPoly(Suite().G2(), Suite().G2().Point().Base(), commits).
		Eval(int(index)).V
}

// VerifyPartial checks one operator's signature share against its own public
// key. Anything that fails here must never reach the aggregator: a single bad
// partial silently corrupts the aggregate, and the node would end up paying gas
// for a transaction that reverts.
func VerifyPartial(commits []kyber.Point, index uint32, seed [32]byte, sig kyber.Point) bool {
	return Verify(SharePublicKey(commits, index), seed, sig)
}
